#!/bin/bash

wget --default-page=public_ip --quiet http://checkip.amazonaws.com

if [ ! -f public_ip ]; then
    sleep 5
    wget --default-page=public_ip --quiet http://checkip.amazonaws.com
fi

if [ ! -f public_ip ]; then
    echo "Error looking up your public IP address using Amazon AWS"
    exit 1
fi

PUBLIC_IP=`cat public_ip`
PUBLIC_HOST=`/home/pi/robot-vpn/ip2host $PUBLIC_IP`
rm -f public_ip

echo "Your public IP address is $PUBLIC_IP"

if [ "$PUBLIC_HOST" != "" ]; then
    echo "Your public host name is $PUBLIC_HOST"
fi
