#!/bin/bash
#
# uninstall-vpn: Uninstall OpenVPN software and configuration on Raspberry Pi
#
# To remove all software and configuration files that were installed using
# the setup-vpn script, simply run this script by bringing up a terminal
# window and entering the following commands:
#	robot-vpn/uninstall-vpn
#	rm -rf robot-vpn

#
# Functions to print messages/prompts in color
#
msg() { echo -e "\e[1;34m$1\e[0m" 1>&2; }	# blue
prompt() { echo -ne "\e[1;33m$1\e[0m" 1>&2; }	# yellow

if [ $EUID -ne 0 ]; then
    msg "[Re-executing with sudo to perform uninstall as root user]"
    exec sudo "$0" "$@"
fi

msg "OpenVPN software and configuration removal for Raspberry Pi"
msg "This command will remove ALL OpenVPN software & configuration!"

prompt "Are you sure you want to continue? [n] "
read REPLY
if [ "$REPLY" != "y" -a "$REPLY" != "yes" ]; then
    msg "Uninstall canceled"
    exit 1
fi

#
# Clear out contents of the VPN configuration repository
# if it exists and we are the designated VPN server
#
PI_HOME=/home/pi
cd $PI_HOME
SETUP_INFO=.vpn-setup-info
PKIDIR=/etc/openvpn/easy-rsa/pki

if [ -f $SETUP_INFO -a -f $PKIDIR/private/VPN_Server.key ]; then
    . ./$SETUP_INFO
    if [ -d $GITHUB_REPO ]; then
	cd $GITHUB_REPO
	git pull
    else
	git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/$GITHUB_USER/$GITHUB_REPO
	cd $GITHUB_REPO
    fi
    for file in `/bin/ls`; do
	rm -f $file
	git add $file
    done
    git commit --message "Clearing VPN configuration"
    git push
fi

#
# Uninstall RPM packages
#
msg "Uninstalling openvpn and bridge-utils packages..."
apt-get -y purge openvpn bridge-utils

#
# Remove configuration, log, and other non-dynamic files
#
msg "Removing VPN configuration, log, and status files..."
rm -rf /etc/openvpn /run/openvpn* /var/log/openvpn*
msg "Removing bridging script..."
rm -f /etc/init.d/bridge /etc/rc2.d/S01bridge
msg "Restoring contents of /etc/dhcpcd.conf file..."
sed -i '/^denyinterfaces eth0/d' /etc/dhcpcd.conf

msg "VPN software and configuration successfully uninstalled"
