#!/bin/sh
#
# uninstall-vpn: Uninstall OpenVPN software and configuration on Raspberry Pi
#
# To remove all software and configuration files that were installed using
# the setup-vpn script, simply run this script by bringing up a terminal
# window and entering the following commands:
#	sudo bash
#	robot-vpn/uninstall-vpn
#	rm -rf robot-vpn

#
# Function to print highlighted (blue) message
#
msg()
{
    echo "\e[1;34m$1\e[0m" 1>&2
}

#
# Function to print highlighted (yellow) prompt message
#
prompt()
{
    echo -n "\e[1;33m$1\e[0m" 1>&2
}

PI_HOME=/home/pi
cd $PI_HOME

VDIR=/etc/openvpn
EDIR=$VDIR/easy-rsa
PKIDIR=$EDIR/pki

msg "OpenVPN software and configuration removal for Raspberry Pi"
msg "This command will remove ALL OpenVPN software & configuration!"

prompt "Are you sure you want to continue [n]? "
read REPLY
if [ "$REPLY" != "y" -a "$REPLY" != "yes" ]; then
    msg "Canceled uninstall"
    exit 1
fi

#
# Uninstall RPM packages
#
msg "Uninstalling openvpn and bridge-utils packages..."
apt-get -y purge openvpn bridge-utils

#
# Remove configuration, log, and other non-dynamic files
#
msg "Removing configuration files..."
rm -rf /etc/openvpn* /run/openvpn* /var/log/openvpn*
rm -f .vpn-setup-info
sed -i '/^denyinterfaces eth0/d' /etc/dhcpcd.conf

msg "VPN software and configuration successfully uninstalled"
