#!/bin/bash
#
# update-server-ip: Reconfigure public-facing OpenVPN server IP address
#
# Written April 2021 by FRC Team 2220 (team2220@eaganrobotics.com)
#
# Usage: robot-vpn/update-server-ip
#
# If you run this on a VPN server, it will update the IP address in the
# personal Github repository configured at setup time.  You will be prompted
# to enter your public-facing IP address which can generally be determined
# by visiting https://whatismyip.com
#
# If you run this on a VPN client, it will consult the personal Github
# repository configured at setup time and use it to update the VPN client
# configuration file.  It will then restart openvpn with the new address.

#
# Helper functions 
#
die() { echo -e "\e[1;31m$1\e[0m" 1>&2; exit 1; } # exit w/error message in red
msg() { echo -e "\e[1;34m$1\e[0m" 1>&2; }	# print message in blue
prompt() { echo -ne "\e[1;33m$1\e[0m" 1>&2; }	# issue prompt in yellow

if [ $EUID -ne 0 ]; then
    exec sudo "$0" "$@"
fi

#
# Initialize constants
#
PI_HOME=/home/pi
SETUP_INFO="$PI_HOME/.vpn-setup-info"
VDIR=/etc/openvpn
CONF=$VDIR/openvpn.conf
EDIR=$VDIR/easy-rsa
PKIDIR=$EDIR/pki

#
# Load previously saved VPN setup info
#
if [ -f $SETUP_INFO ]; then
    . $SETUP_INFO
else
    die "Missing VPN setup info; you may need to re-run install"
fi

#
# Make sure VPN configuration is available
#
if [ ! -f $PI_HOME/$GITHUB_REPO/VPN_Server_ipaddr ]; then
    die "Error: VPN configuration repository missing; you may need to reinstall"
fi

if [ ! -d $VDIR ]; then
    die "Error: No VPN installation detected; you may need to reinstall"
fi

cd $PI_HOME/$GITHUB_REPO
git pull || die "You may need to reinstall"

#
# Determine the current IP address of the VPN server
#
CUR_IP=`grep "^remote .* 1194" $CONF | sed -e 's/^remote //' -e 's/ .*$//'`

#
# Determine whether we are running on the VPN server or a VPN client
#
if [ -f $PKIDIR/issued/VPN_Server.crt ]; then

    msg "Detected VPN server on this system on IP address $CUR_IP ..."

    prompt "Are you sure you want to change the VPN server IP address? [n] "
    read REPLY
    if [ "$REPLY" != "y" -a "$REPLY" != "yes" ]; then
	die "Update canceled"
    fi

    prompt "Enter the new VPN server IP address or host name: "
    read SERVER_IPADDR
    if [ "x$SERVER_IPADDR" = "x" ]; then
	die "Error: No server IP address specified, exiting"
    fi

    #
    # Update VPN server IP address in Github repo
    #
    cd $PI_HOME/$GITHUB_REPO
    echo $SERVER_IPADDR > VPN_Server_ipaddr
    git add VPN_Server_ipaddr
    git commit --message="Updated VPN server IP address"
    git push
    msg "Updated VPN server IP address in personal Github repository."
    msg "To complete this IP address change, you must run this script"
    msg "on each of the VPN clients as well."

elif [ -d $VDIR ]; then

    msg "Detected VPN client on this system..."
    msg "The configured VPN server IP address is $CUR_IP"

    NEW_IP=`cat VPN_Server_ipaddr`

    if [ "$CUR_IP" != "$NEW_IP" ]; then

	msg "The new VPN server IP address is now $NEW_IP"

	#
	# Update VPN server IP address in client configuration file
	#
	sed -i "s/^remote $CUR_IP 1194$/remote $NEW_IP 1194/" $CONF
	msg "Updated server IP address in client configuration file"

	#
	# Restart bridge and openvpn client
	#
	systemctl stop openvpn || die "Unable to stop openvpn; please reboot"
	systemctl stop bridge || die "Unable to stop bridge; please reboot"
	systemctl start bridge || die "Unable to start bridge; please reboot"
	systemctl start openvpn || die "Unable to start openvpn; please reboot"
	msg "Restarted openvpn client"

    else
	msg "The server IP address has not changed, so no update is necessary"
    fi

else
    die "No VPN client or server detected on this system"
fi
