#!/bin/bash
#
# update-server-ip: Reconfigure public-facing OpenVPN server IP address/port
#
# Written April 2021 by FRC Team 2220 (team2220@eaganrobotics.com)
#
# Usage: robot-vpn/update-server-ip
#
# If you run this on a VPN server, it will update the IP address and/or port
# number in the personal Github repository configured at setup time.  You will
# be prompted to enter your public-facing IP address which can generally be
# determined by visiting https://whatismyip.com .
#
# If you run this on a VPN client, it will consult the personal Github
# repository configured at setup time and use it to update the VPN client
# configuration file.  It will then restart openvpn with the new address/port.

#
# Helper functions 
#
die() { echo -e "\e[1;31m$1\e[0m" 1>&2; exit 1; } # exit w/error message in red
msg() { echo -e "\e[1;34m$1\e[0m" 1>&2; }	# print message in blue
prompt() { echo -ne "\e[1;33m$1\e[0m" 1>&2; read $2; } # issue prompt in yellow

if [ $EUID -ne 0 ]; then
    exec sudo "$0" "$@"
fi

#
# Initialize constants
#
PI_HOME=/home/pi
SETUP_INFO="$PI_HOME/.vpn-setup-info"
VDIR=/etc/openvpn
CONF=$VDIR/openvpn.conf
EDIR=$VDIR/easy-rsa
PKIDIR=$EDIR/pki

#
# Load previously saved VPN setup info
#
if [ -f $SETUP_INFO ]; then
    . $SETUP_INFO
else
    die "Missing VPN setup info; you may need to re-run install"
fi

#
# Make sure VPN configuration is available
#
if [ ! -f $PI_HOME/$GITHUB_REPO/VPN_Server_ipaddr ]; then
    die "Error: VPN configuration repository missing; you may need to reinstall"
fi

if [ ! -d $VDIR ]; then
    die "Error: No VPN installation detected; you may need to reinstall"
fi

cd $PI_HOME/$GITHUB_REPO
git pull >/dev/null || die "You may need to reinstall"

#
# Determine the registered IP address and port number of the VPN server
#
SERVER_IPADDR=`head -1 VPN_Server_ipaddr`
SERVER_PORT=`tail +2 VPN_Server_ipaddr`

#
# Determine whether we are running on the VPN server or a VPN client
#
if [ -f $PKIDIR/issued/VPN_Server.crt ]; then

    msg "Detected VPN server on this system"
    msg "IP address is $SERVER_IPADDR, UDP port number is $SERVER_PORT"

    prompt "Are you sure you want to change these values? [n] " REPLY
    if [ "$REPLY" != "y" -a "$REPLY" != "yes" ]; then
	die "Update canceled"
    fi

    CHANGED=n
    prompt "Enter the new IP address or host name [$SERVER_IPADDR]: " REPLY
    if [ "$REPLY" != "" ]; then
	SERVER_IPADDR=$REPLY
	CHANGED=y
    fi

    prompt "Enter the new UDP port number [$SERVER_PORT]: " REPLY
    if [ "$REPLY" != "" ]; then
	SERVER_PORT=$REPLY
	CHANGED=y
    fi

    #
    # Update VPN server IP address and port number in Github repo
    #
    if [ $CHANGED = "y" ]; then
	cd $PI_HOME/$GITHUB_REPO
	cat << EOF > VPN_Server_ipaddr
$SERVER_IPADDR
$SERVER_PORT
EOF
	git add VPN_Server_ipaddr
	git commit --message="Updated VPN server IP address/port"
	git push
	msg "Updated VPN server IP address/port in personal Github repository."
	msg "To complete this change, you must run this script on each of the"
	msg "VPN clients as well."
    else
	msg "No change in IP address or port number; nothing updated"
    fi

elif [ -d $VDIR ]; then

    msg "Detected VPN client on this system"
    OLD_IPADDR=`grep "^remote " | sed -e 's/^remote //' -e 's/ .*$//'`
    OLD_PORT=`grep "^remote " | sed -e 's/^remote //' -e 's/ .*$//'`
    msg "Current server IP address is $OLD_IPADDR, UDP port number is $OLD_PORT"

    if [ $OLD_IPADDR != $SERVER_IPADDR -o $OLD_PORT != $SERVER_PORT ]; then

	msg "The new server IP address is $SERVER_IPADDR"
	msg "The new server UDP port number is $SERVER_PORT"

	#
	# Update VPN server IP address in client configuration file
	#
	sed -i "s/^remote .*$/remote $SERVER_IPADDR $SERVER_PORT$/" $CONF
	msg "Updated server IP address/port in client configuration file"

	#
	# Restart bridge and openvpn client
	#
	systemctl stop openvpn || die "Unable to stop openvpn; please reboot"
	systemctl stop bridge || die "Unable to stop bridge; please reboot"
	systemctl start bridge || die "Unable to start bridge; please reboot"
	systemctl start openvpn || die "Unable to start openvpn; please reboot"
	msg "Restarted openvpn client"

    else
	msg "Server IP address and port have not changed; no update necessary"
    fi

else
    die "No VPN client or server detected on this system"
fi
